# Basics of machine learning

### Imports

Essential import for this tutorial which will use in different part of tutorial

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import explained_variance_score


from sklearn import datasets

from sklearn import linear_model
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier


##### Error mesurment in sklearn 

In [13]:
# import numpy as np
# from sklearn.metrics import mean_absolute_error
# from sklearn.metrics import mean_squared_error
# from sklearn.metrics import explained_variance_score

actual = np.array([1,2,3,4])
predect = np.array([1.2,2.1,3.3,4.1])
mae = mean_absolute_error(actual, predect)
mse = mean_squared_error(actual, predect)

var = explained_variance_score(actual, predect)
print("Mean Abs Error : ", mae)
print("Mean Sqr Error : ", mse)
print("Mean Var Error : ", var)

Mean Abs Error :  0.17499999999999988
Mean Sqr Error :  0.03749999999999996
Mean Var Error :  0.9945


### Dataset Pripration

We are using sklearn iris dataset 

In [14]:
# import pandas as pd
# from sklearn import datasets

iris_set = datasets.load_iris()
print("Iris set count:", len(iris_set))
data = pd.DataFrame(iris_set.data[:,0:4])
data.columns = ['a', 'b', 'c', 'd']
target = pd.DataFrame(iris_set.target)
target.columns = ['e']

print("Data shape:", data.shape)
print("target shape:", target.shape)

#'target_names': array(['setosa', 'versicolor', 'virginica'], 

Iris set count: 6
Data shape: (150, 4)
target shape: (150, 1)


### Linear Regression

Linear Regression model 

In [15]:
# from sklearn import linear_model

model = linear_model.LinearRegression()
reg = model.fit(data, target)
predict = model.predict([[1,1,1,1]])
print(predict) 
# 0.87 near to 1
print(model.coef_)

[[0.87240699]]
[[-0.11190585 -0.04007949  0.22864503  0.60925205]]


### Logistic Regration

Logistic Regration Used in classification problem (binary or multi)

In [16]:
# from sklearn import linear_model

model = linear_model.LogisticRegression()
reg = model.fit(data, target)
predict = model.predict([[0,1,2,2]])
print(predict) 
print(model.coef_)

[2]
[[ 0.41021713  1.46416217 -2.26003266 -1.02103509]
 [ 0.4275087  -1.61211605  0.5758173  -1.40617325]
 [-1.70751526 -1.53427768  2.47096755  2.55537041]]


/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [6]:
from sklearn import svm

# SVM
svc = svm.SVC(kernel='linear', C=0.05).fit(data, target)
reg = svc.fit(data, target)
predict = reg.predict([[0,1,2,2]])
print("Priciction: ", predict)

Priciction:  [0]


/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
from sklearn.tree import DecisionTreeClassifier

#Desission Tree
model = DecisionTreeClassifier(criterion='entropy')
reg = model.fit(data, target)
predict = model.predict([[1,1,1,1]])
print(predict)

[1]


In [8]:
from sklearn.ensemble import RandomForestClassifier

#Random Forest
model = RandomForestClassifier()
reg = model.fit(data, target)
predict = model.predict([[1,1,1,1]])
print(predict)

[1]


/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


In [9]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# In[]
#K Mean cluster

colormap = np.array(['blue', 'red', 'black'])
plt.scatter(data.a, data.b, c=colormap[target.e])
plt.title('Data')
plt.show()

model = KMeans(n_clusters=3, random_state=5).fit(target)
predict = model.predict
print(predict)
label = model.labels_
print(label)
cluster_center = model.cluster_centers_
print(cluster_center)
plt.polar(cluster_center, '--or')
plt.show()

<Figure size 640x480 with 1 Axes>

<bound method KMeans.predict of KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=5, tol=0.0001, verbose=0)>
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[1.]
 [0.]
 [2.]]


<Figure size 640x480 with 1 Axes>

In [10]:
from sklearn.neighbors import KNeighborsClassifier

#KNeighbors Classifier
model = KNeighborsClassifier()
reg = model.fit(data, target)
predict = model.predict([[1,1,1,1]])
print(predict)

[0]


/home/prashant/anaconda3/envs/ML/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """


### Prashant Kumar